ALTER TABLE `external_school_post_requests`
  ADD COLUMN `offerCategory` VARCHAR(80) NULL,
  ADD COLUMN `originalPrice` VARCHAR(100) NULL,
  ADD COLUMN `offerPriceDiscount` VARCHAR(255) NULL,
  ADD COLUMN `couponCode` VARCHAR(100) NULL,
  ADD COLUMN `offerValidFrom` DATE NULL,
  ADD COLUMN `offerValidUntil` DATE NULL,
  ADD COLUMN `howToRedeem` TEXT NULL,
  ADD COLUMN `redemptionUrl` VARCHAR(500) NULL,
  ADD COLUMN `termsAndConditions` TEXT NULL,
  ADD COLUMN `offerContactInfo` TEXT NULL,
  ADD COLUMN `offerPublishStatus` VARCHAR(20) NULL,
  ADD COLUMN `discountType` VARCHAR(20) NULL,
  ADD COLUMN `discountValue` VARCHAR(100) NULL,
  ADD COLUMN `maximumDiscount` VARCHAR(100) NULL,
  ADD COLUMN `minimumPurchase` VARCHAR(100) NULL,
  ADD COLUMN `usageLimit` VARCHAR(100) NULL,
  ADD COLUMN `redemptionsPerStudent` VARCHAR(100) NULL,
  ADD COLUMN `applicableLocations` VARCHAR(500) NULL,
  ADD COLUMN `offerAvailability` VARCHAR(20) NULL,
  ADD COLUMN `studentIdRequired` BOOLEAN NOT NULL DEFAULT false;
