ALTER TABLE `external_school_post_requests`
  ADD COLUMN `contentType` VARCHAR(20) NOT NULL DEFAULT 'event',
  ADD COLUMN `companyName` VARCHAR(255) NULL,
  ADD COLUMN `companyLogoUrl` VARCHAR(500) NULL,
  ADD COLUMN `jobType` VARCHAR(50) NULL,
  ADD COLUMN `workMode` VARCHAR(50) NULL,
  ADD COLUMN `jobLocation` VARCHAR(500) NULL,
  ADD COLUMN `eligibilityRequirements` TEXT NULL,
  ADD COLUMN `skillsRequired` TEXT NULL,
  ADD COLUMN `experienceRequired` VARCHAR(80) NULL,
  ADD COLUMN `salaryStipend` VARCHAR(255) NULL,
  ADD COLUMN `applicationDeadline` DATE NULL,
  ADD COLUMN `applicationMethod` VARCHAR(20) NULL,
  ADD COLUMN `applicationTarget` VARCHAR(500) NULL,
  ADD COLUMN `contactPerson` VARCHAR(255) NULL,
  ADD COLUMN `contactEmail` VARCHAR(255) NULL,
  ADD COLUMN `contactPhone` VARCHAR(50) NULL,
  ADD COLUMN `postedByOrganization` VARCHAR(255) NULL,
  ADD COLUMN `jobPublishStatus` VARCHAR(20) NULL,
  ADD COLUMN `applyButtonEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `saveJobButtonEnabled` BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN `applyButtonUrl` VARCHAR(500) NULL;
